// <auto-generated />
using System;
using MesaDeAyuda.Data.Persistency.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MesaDeAyuda.Data.Persistency.Migrations
{
    [DbContext(typeof(MesaDeAyudaContext))]
    [Migration("20250921214356_AddContraseniaAndFechaCreado")]
    partial class AddContraseniaAndFechaCreado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Area")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioRutCreador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioRutTecnico")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioRutCreador");

                    b.HasIndex("UsuarioRutTecnico");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("Rut")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrasenia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Rut");

                    b.ToTable("Usuario", "MesaDeAyuda");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("MesaDeAyuda.Domain.Entities.Usuario", "UsuarioRutCreadorNavigation")
                        .WithMany("ListTicketCreado")
                        .HasForeignKey("UsuarioRutCreador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MesaDeAyuda.Domain.Entities.Usuario", "UsuarioRutTecnicoNavigation")
                        .WithMany("ListTicketTecnico")
                        .HasForeignKey("UsuarioRutTecnico");

                    b.Navigation("UsuarioRutCreadorNavigation");

                    b.Navigation("UsuarioRutTecnicoNavigation");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ListTicketCreado");

                    b.Navigation("ListTicketTecnico");
                });
#pragma warning restore 612, 618
        }
    }
}
